### ISSUE TITLE
T3640 Issue #1

### ISSUE THREAD

**Issue by Grisu70** [weblogix/hackintosh-dell-precision-3240-compact-comet-lake-opencore#24]
Hi,
your configuration worked almost immediately on my my T3640.
I have 2 issue , this is the first 

I have 2 DP monitor
during boot, 98% of the times, primary display turn to PINK gradient.
I had to switch it off and on get back to normal color.
Never happens on window 10. if I invert the 2 monitor the problem switch to the other monitor.

Fabrizio

**Comment by weblogix** [comment]
I've had issues with the HD 630 and my monitor too, specifically hdmi audio disappears after waking up from sleep.  I have a feeling that the HD 630 settings just aren't correct, and Whatevergreen isn't detecting everything (just my hunch).

I've read of others having pink screens and being able to fix it with injecting their monitors EDID into their OC config. You can give it a try - https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md#edid

**Comment by weblogix** [comment]
Personally, I decided to stop using the HD630 and installed an old Nvidia Quadro K420 (while still using the HD630 for quicksync) and all my issues disappeared.  So the drivers for Nvidia are stable, while Intel HD 630's probably can't detect all the proper settings.
