### ISSUE TITLE
T3640 Issue #2

### ISSUE THREAD

**Issue by Grisu70** [weblogix/hackintosh-dell-precision-3240-compact-comet-lake-opencore#25]
Hi,
your OC configuration is almost ok, this si the 2nd issue.
I have installed Big Sur 11.3 (and trying to update to 11.4)
some USB seems not working , any suggestion ?
This could be as the OC is configured for T3240 I/o T3640

Fabrizio

**Comment by weblogix** [comment]
I'm not sure why USB isn't working for you.  I would try the USB Mapping guide - https://dortania.github.io/OpenCore-Post-Install/usb/intel-mapping/intel.html.

Like the repo description says, this configuration is for a Dell Precision 3240 Compact.
