### ISSUE TITLE
I have a q about ru tools

### ISSUE THREAD

**Issue by fowlmouse** [weblogix/hackintosh-dell-precision-3240-compact-comet-lake-opencore#6]
can someone help explaining how to used ru tool SOP and how to build into mackintosh install usb flash device? Thanks

**Comment by weblogix** [comment]
https://dortania.github.io/ should have all that you need to get Mac OS up and running, including how to make a bootable USB drive (https://dortania.github.io/OpenCore-Post-Install/universal/oc2hdd.html#grabbing-opencore-off-the-usb)

I used this link to figure out how to use RU (https://www.reddit.com/r/hackintosh/comments/hz2rtm/cfg_lockunlocking_alternative_method/)

Goodluck!

**Comment by weblogix** [comment]
No issue to resolve.
